### ISSUE TITLE
ArgumentOutOfRangeException when trying to compress large files

### ISSUE THREAD

**Issue by WhyNot-hub** [FACS01-01/VRC-Hotswap#3]
I encountered an ArgumentOutOfRangeException while attempting to compress a large file (over 500 MB in size) using VRC Hotswap Compressor.exe. The error occurs when I attempt to unpack the file decomp2.vrca manually. This only happens with large files.

Unhandled exception. System.ArgumentOutOfRangeException: Non-negative number required. (Parameter 'count')
   at System.IO.BinaryReader.ReadBytes(Int32 count)
   at AssetsTools.NET.AssetBundleFile.Unpack(AssetsFileReader reader, AssetsFileWriter writer, ICodeProgress progress)
   at AssetsTools.NET.Extra.BundleHelper.UnpackBundle(AssetBundleFile file, Boolean freeOriginalStream, ICodeProgress progress)
   at AssetsTools.NET.Extra.BundleFileInstance..ctor(Stream stream, String filePath, String root, Boolean unpackIfPacked)
   at AssetsTools.NET.Extra.AssetsManager.LoadBundleFile(Stream stream, String path, Boolean unpackIfPacked)
   at AssetsTools.NET.Extra.AssetsManager.LoadBundleFile(FileStream stream, Boolean unpackIfPacked)
   at AssetsTools.NET.Extra.AssetsManager.LoadBundleFile(String path, Boolean unpackIfPacked)
   at FACS01_Bundle_Comp_Decomp.Program.CompressBundle(String decompressed_path, String compressed_path_result)
   at FACS01_Bundle_Comp_Decomp.Program.Main(String[] args)
  
**Unity gives me this Exeption**
   
   Hotswap failed. New Avatar file ended up malformed.

  UnityEngine.Debug:LogError (object)
  VRCHotswap/<>c:<HS4>b__29_0 (UnityEngine.AsyncOperation) (at Assets/VRC Hotswap/Editor/VRCHotswap.cs:471)
  UnityEngine.AsyncOperation:add_completed (System.Action`1<UnityEngine.AsyncOperation>)
  VRCHotswap:HS4 () (at Assets/VRC Hotswap/Editor/VRCHotswap.cs:463)
  VRCHotswap/<>c:<compress>b__28_3 (object) (at Assets/VRC Hotswap/Editor/VRCHotswap.cs:438)
  UnityEngine.UnitySynchronizationContext:ExecuteTasks ()

**Comment by FACS01-01** [comment]
I haven"t kept this tool updated, and I wouldn't consider it safe to use anymore.
By the meantime look for other hotswap apps. Can't promise to revisit this tool soon.
